board: [ "nice_nano_v2" ]
shield: [ "corne_left", "corne_right" ]
include:
  - board: nice_nano_v2
    shield: mykeyboard3x3
  - board: bdn9_rev2
  - board: nice_nano_v2
    shield: reviung41
  - board: nice_nano_v2
    shield: corne_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: corne_left_with_studio